### ISSUE TITLE
re2 .v2.15 brad zombie lead to crash

### ISSUE THREAD

**Issue by kendosrando** [IntelOrca/biorand#157]
Seed: R520-9J1V-ZJB73JPKK611
 using the handgun(all types)  to shoot at brad zombie had a low chance lead to crash,  sparkgun, bowgun and shotgun are ok

**Comment by kendosrando** [comment]
This glitch exist for quite a long time, it happens no matter what room they spawn, even the magnum has the same if you got bad luck, not a serious problem, but sometimes it's annoying when they block my way out and I only have a pistol

https://user-images.githubusercontent.com/122246002/212458401-58dbd5ab-afa5-437d-9a07-377fb57316e3.mp4

**Comment by kendosrando** [comment]
And there is another problem as you can see when I set the segment number and room size to maximum

https://user-images.githubusercontent.com/122246002/212533424-2d6c61a6-6338-4766-840d-e6f9ce12ecce.mp4

even if I don't go back to the first area, still can be switched to Ada sooner or later in the next exploration

**Comment by IntelOrca** [comment]
The ada switch is a different bug and that has been fixed.

**Comment by kendosrando** [comment]
It's fixed in v2.16? I found out it's nothing to do about the setting, only if the first area is connected to this room, it'll happen

**Comment by IntelOrca** [comment]
Which issue are you referring to? The one where it switches to Ada is fixed.

**Comment by kendosrando** [comment]
sorry to let you confused, I mean except for the brad zombie crash problem, the Ada switch problem is still in v2.15, I've tried three different seeds the first area is connected to this elevator room, these are all switches to Ada when I into the next room, you can test this one    Leon-A: R520-QYT1-ZJC73KZKK611 (set the segment size and room size to maximum)

**Comment by IntelOrca** [comment]
But it was fixed in v2.1.6.

**Comment by kendosrando** [comment]
OH, I'm so sorry, I didn't notice the new update already coming, thank you for your patience
